# Generated by Django 3.2.9 on 2021-12-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
